#!/bin/bash

# swaps contents of subtree of a svn working copy $dst with the contents of $src,
# without getting .svn directory mayhem and svn throwing all kinds of errors at you

# dependencies: svn, rsync, findutils, awk, ifne from moreutils, libui-sh
source /usr/lib/libui.sh

src=$1
dst=$2

[ -n "$src" -a -d "$src" ] || die_error '$1: src dir'
[ -n "$dst" -a -d "$dst" ] || die_error '$2: dst dir'

# remove everything but the directory structure with .svn directories and files in it in dst.
find $dst -type f | grep -v '\.svn' | xargs rm
# svn rm directories in dst which are not in the src dir
for dir_dst in `find $dst -type d | grep -v '\.svn'`; do
	dir_src=${dir_dst/$dst/$src}
	if [ -d $dir_src ]; then
		#echo "$dir_src exists. not doing anything"
		true
	else
		echo "$dir_src does not exist. removing $dir_dst"
		svn rm $dir_dst
	fi
done
# copy all new files and directories into dst, leaving .svn directories in dst untouched
rsync -a $src $dst

echo "svn adding new files/dirs, svn rm'ing removed files/dirs"
svn status $dst | awk '/^?/ {print $2}' | ifne xargs svn add
svn status $dst | awk '/^!/ {print $2}' | ifne xargs svn rm
echo "should be ready for commit:"
echo "svn status $dst"
svn status $dst
